language: node_js
node_js:
  - "stable"
env:
  global:
    - CC_TEST_REPORTER_ID=8b4fe4c25416a25bbf6c697cb2c078fc75c010a292eebed0b3cab889c6603852

install:
  - npm install

cache:
  directories:
    - "node_modules"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  npm test

after_success:
  -  npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
